### ISSUE TITLE
can you post pre compiled bin file for 9xr pro

### ISSUE THREAD

**Issue by geofrancis** [adriano65/opentx-2.0.14#1]
can you post a compiled bin file for the 9xr pro so i can use frsky and mavlink.

**Comment by adriano65** [comment]
Just uploaded in pre-release section:-)
it seems to work with 2.0.14 eeproms but havent tested in deep

 i don't remember if i loaded via companion or microSD, try both.

let me know if it works for you :-)

**Comment by FlyingHighInTheSky** [comment]
I have a 9XR and wanted to try it. Does the 9XR Pro work on the 9XR as well. I tried to compile the source but got some error messages.

**Comment by geofrancis** [comment]
its kind of working but im not getting data through and on the mavlink screen its just the PKT DROP counter thats climbing.

**Comment by geofrancis** [comment]
i see your also missing ppm2 out

**Comment by geofrancis** [comment]
i think my problem is that the comports on the 9xr pro are rs232 not uart?

**Comment by FlyingHighInTheSky** [comment]
Couldn't upload the 9XR Pro to the 9XR, the radio turned off in the middle of writing. I tried the 9X version and i uploaded it on the 9XR. I will test tomorrow the frsky telemetry. I can't test the mavlink because my apm got damaged. There are two things i notice tonight: there are no voices. I have the Megasound9X installed on the 9XR and voices are great to have there and the backlight doesn't turn on. I will test tomorrow the frsky and report back.

**Comment by geofrancis** [comment]
megasound is not supported with opentx

**Comment by adriano65** [comment]
@geofrancis 
i use 9600 baud second com port on 9xrpro (futaba port)
Did you change baudrate on mavlink menu? (default is 4800)

**Comment by adriano65** [comment]
@albeagle007 
Just uploaded a 9xr128 version.
i haven't megasound hw-mod and i can't help there
try it if you want :-)

**Comment by FlyingHighInTheSky** [comment]
Thank you, i will try it and report back. When i try to compile the source code i get an error about view_frsky.cpp. Any suggestion

![comperror](https://cloud.githubusercontent.com/assets/16160718/11609697/0c665a9a-9b8e-11e5-9075-9c210374c23b.jpg)

**Comment by geofrancis** [comment]
i was trying to use it at 57600. but i will try with 19200.

**Comment by FlyingHighInTheSky** [comment]
@geofrancis the opentx with mavlink i have supports megasound9x, i'm using sounds on the radio.

**Comment by geofrancis** [comment]
i got it working on the tx and rx next to com2, the only thing not displaying properly is the flight mode.it just says "UNKN MAV TYPE"

**Comment by FlyingHighInTheSky** [comment]
Hi there Adriano and thank you for the great work. I installed the 9xr128 version and everything is working with FrSky. Backlight OK, Sound OK, Telemetry OK. The only thing i noticed was the Radio Modes. You have deleted them, so you can't switch between M1, M2, M3 and M4. It is only set to Mode 2 i think but i use Mode 1 (actually Mode 3). If you could fix that it would be great. I still have to test the Mavlink when i get the APM and Pixhawk. Thanks again for the hard work :)

**Comment by geofrancis** [comment]
with bluetooth mode on this firmware is it bidirectional? can i receive and send telemetry via it?

**Comment by adriano65** [comment]
@albeagle007
just updated a master version with missed frsky file and makefile.
It should work, but i haven't tested it... (I have to check Radio Modes missed ;-)

**Comment by geofrancis** [comment]
any idea why flight modes are coming up on the 9xr pro screen as "UNKN MAV TYPE" ?

will you be able to merge your changes onto 2.1.5+ i really need the selectable ppm2 out so i can use my frsky diy module internally and my openlrs in the module bay without resorting to switches.

can the mavlink telemetry values be selected like the frsky ones so that custom warnings can be assigned to the values.

**Comment by adriano65** [comment]
@geofrancis
depends on APM type you load on plane/quad (that code don't recognize yet)
I am using ardupilot-3.1.1 and it shows OK.
Maybe we have to update MAVLINK #defines in this opentx version
(see view_mavlink.cpp -> print_mav_mode)

**Comment by geofrancis** [comment]
im running arducopter 3.2.1 on a pixhawk, are you running a cx-20 or something with that old version?

 i used to have this problem with opentx-mavlink on my 9x when using arduplane.

**Comment by FlyingHighInTheSky** [comment]
Downloaded the new repository, but it looks like the source code is for the 9XR Pro. Could you please uplod the 9XR 128 source code. I also have a question. While compiling i get: bash.exe: warning: could not find /tmp, please create! I created /tmp manually in the radio and src folder but didn' help. Any suggestion?

Thanks
AlbEagle

**Comment by adriano65** [comment]
@albeagle007
to compile for 9xr128 you have to change the define in makefile (line 55 -> PCB = 9XR128)
and comment out PCB = 9XRPRO

..about tmp and bash -> it is a compiler config: can't help.

**Comment by adriano65** [comment]
@geofrancis
i use 3.1.1 because i modified it for double link minimosd and openlrs at different speeds (57600 and 9600) ..

it is my intention to merge with 2.1.5 but now i want to make it work on my glorious SKY9X :-)
Let me check mode menus and ppm2

**Comment by geofrancis** [comment]
i use the gitsly fork of openlrsng, it has mavlink flow control so i can run the serial rate at 57600 along with my minimosd and still get all data through with a 19200 air rate on openlrsng. then its connnected to a bluetooth serial adapter for connecting to my phone/tablet.

albeagle007 wrote it up here when i talked him through building his.
http://flyingforfun.weebly.com/open-lrs.html

https://github.com/openLRSng/openLRSng/tree/gitsly

**Comment by adriano65** [comment]
@albeagle007
mode menu seems to work...
binary is in pre-release 0.2.14 Try it if you want :-)

**Comment by geofrancis** [comment]
i see you done the ppm2 output for 9xr pro. as far as 9xr pro is a clone of ersky9x so it should work on yours too.

also on com1 with 9xr pro it has tx and rx on a single pin. any idea how i could convert it back to regular tx rx?

**Comment by adriano65** [comment]
i don't use PPM2 on sky9x, but i hope it will work for you. I am testing mavlink statuses on 9xrpro
and 9xr128 and a bad error on start.

about 9xrpro com1, i don't have schematics but i am sure it can be done with some
soldering. Every UART has distinct tx/rx pins even if 9xrpro board join them together
with some kind of resistors.

**Comment by geofrancis** [comment]
how does your firmware handle the ports? i want to run frsky into com1 and mavlink into com2 will the firmware just listen to both or is there a way to select a com port?

**Comment by adriano65** [comment]
I am developing a way to associate one com port to a protocol (mavlink, frsky, others)
on a model based selection.
... and copy serial data on a bluetooth module, to see data in field with droidplanner or something.

I will let you know :-)

**Comment by geofrancis** [comment]
ok let me know when its good enough for testing and il flash it to my 9xr pro.

did you find out why the modes were not working ? 
would it be possible to use the mavlink data as variables so that alarms can be set similar to frsky?

**Comment by adriano65** [comment]
I changed telemetry serial selection: now you can choose which com gets
telemetry data in general menu (telemetry mirror not implemented yet)

I am also trying to import eeprom.
I add a log capability for mavlink on uSD.

About apm modes, i am debugging
and i write raw data to menu.

I'll release something in the next days
Thank you for your help

**Comment by FlyingHighInTheSky** [comment]
I tried the firmware with Mavlink, it is not working, it is only dropping the packets. FrSky works great though. I have the 9XR.  I'm using the setup i have described here:

http://flyingforfun.weebly.com/open-lrs.html

Any chance you can update the 9xr hext too?

Best regards
AlbEagle

**Comment by FlyingHighInTheSky** [comment]
@adriano65 
I tried the mavlink again, the strange thig is, I can connect to mission planner through FTDI, baudrate set at 19200 (everything i have is set to that baudrate) and everything works on MP on PC, i just don't get anything shown on the screen of the 9XR. I only get dropped packets.

AlbEagle

**Comment by adriano65** [comment]
Did you check the mavlink baudrate in model setup ? i usually test it at 9600 and it works..
maybe i made some mistakes on other speeds :-(
Anyway i am configuring the SITL simulator for mavlink so i can check better next days..

**Comment by FlyingHighInTheSky** [comment]
It's working :) I didn't see you posted a second pre-release for the 9XR 128. Thank you for your great work. I will test it tomorrow in details and i will let you know. I have two S500 quads. I want to use both of them with only one radio. The first one has a Pixhawk Lite, 3axis gimbal, sj4000, 6s setup and i'm using it with OpenLRS. The second one i'm going to use only for fpv with APM 2.8 FrSky DF Combo (DJT + D8R II Plus) 3s setup. Its great being able to only swap the Tx Modules and change the protocol on the handset and use Mavlink/Frsky. Thanks again :+1:

**Comment by adriano65** [comment]
Glad to read it is working:-)
i have to enhance mavlink status on second menu, but thanks for testing:-)

**Comment by FlyingHighInTheSky** [comment]
@adriano65 
Today i tested the FrSky, it is working great. Tomorrow i will test the mavlink. I think i saw some flight modes not displayed on the 9xr screen but i will test it tomorrow in more details and let you know. I hope weather will be good. It's been foggy for a while here

![20151224_095322](https://cloud.githubusercontent.com/assets/16160718/12008278/ab1fff8e-ac31-11e5-8992-241f1eca870c.jpg)

I live down there under the fog lol .
Pictures taken from the quad here would be awesome i think :)

**Comment by adriano65** [comment]
:-) Wonderful picture!
I'd like to dive in the fog with my FPV bixler2
with mobius recording Full-HD! :-)

**Comment by FlyingHighInTheSky** [comment]
My Bixler 2 is laying in my room just because i don't have a carbon spar for the wings (I broke it in a tip stall above a cemetery (I guess i shouldn't have flown there lol) but since we were working there, i thought i would record the area. It was the first flight after upgrading the motor (jello effect, no camera dampening).

https://www.youtube.com/watch?v=fnAEcyqrxRA

I will purchase another Orange LRS receiver for my Bixler 2 so i will be able to fly 2 Quads and the Bixler with the 9XR. I will make a video about how to setup Mavlink and OpenLRS with your firmware and upload it to my youtube channel. I will direct people to your work here. I think there are a lot of others that would like to setup systems like this.

Best regards
AlbEAGLE

**Comment by FlyingHighInTheSky** [comment]
@adriano65 

Hi there adriano

Is it possible to display Current Flight mode on Frsky Telemetry screen. Also some flight modes are not displaying on the Mavlink telemetry screen. Instead of the flight mode you get numbers for example if i switch to RTL, i get Current Mode 89. Also on the left upper corner of the 9xr screen it says Plane (should be Copter or Quad :) )

I wanted to let you know about these issues.

Happy New Year :)
AlbEagle

**Comment by adriano65** [comment]
Thank you for your tests :-)
I was releasing a version with correct flight modes but i must check why
copter are not recognized.

I must check APM arducopter code...

**Comment by adriano65** [comment]
hi AlbEagle,
i just released 0.2.17 version with corrections to (hopefully) display
Current flight mode.
I had no time to load and check, but next days i will.

I am working on companion (linux) to try loading EEproms with models
but i have a bad bug that even prevents loads of bootloader on 9xrpro...

Have a good new year :-)
Adriano

**Comment by geofrancis** [comment]
it looks good, the only mode that is not working is POSHOLD it just shows as mode 16.

how do you enable the sd gps logging?

**Comment by adriano65** [comment]
Thank you for your quick test !
I'll check pos hold.
To enable gps log, you have to go to special functions menu, choose
a switch (i use RUD switch on left) 
and assign SD Logs item.
the last item is saving speed on uSD, i use 0.5 seconds

Bye

**Comment by geofrancis** [comment]
i might set that to always on lol. 

the only thing missing is being able to use the mavlink values for alarms like low voltage.

even if you just set it to map the mavlink values into the frsky field so they can be selected with logical switches.

**Comment by adriano65** [comment]
Eh eh ;-)
Just thinking about it...
Let me some time to organize
and, please tell me about Logs

**Comment by FlyingHighInTheSky** [comment]
@adriano65 

Flight modes are showing now thank you. If i translate the en.h to albanian.h would you help me to integrate that language and show on my handset. I tried it myself but it is showing some errors while compiling. There must be something with the length of the strings maybe. Is there anything i should know before starting to translate

Thanks
AlbEagle

**Comment by adriano65** [comment]
@albeagle007 
Glad to know modes working better now :-)
I can't help you much about translations: i am too busy with companion and mavlink bidirectional
communication (to slow down speed and increase TX distance).
Anyway, you have to absolutely maintain strings length and not change any \0, \r in the end
HAPPY NEW YEAR!!

**Comment by geofrancis** [comment]
i noticed you have the telemetry port configuration in the radio configuration, does that mean it would have to be changed whenever i switched profile from openlrs airfraft to frsky aircraft if i have them on com1 and com2

**Comment by adriano65** [comment]
@geofrancis 
Yes, you are right. I had spare bits in General Menu (radio menu) and i was trying to keep low
eeprom usage for old 9X.
The problem you pointed out is even worst on Taranis. It has internal frsky com0 and external
telemetry/debug/bluetooth port to connect openlrs-ng serial.
If you want, open an issue to keep track of this enhancement

**Comment by geofrancis** [comment]
you could remove that option for 9x and 9xr since they only have com0

**Comment by adriano65** [comment]
I am preparing a version with com settings on menumodel basis.
But my taranis still not work with internal module.
9XRPRO works but menu model is still items-jumping.
...
just to let everybody know :-)

**Comment by geofrancis** [comment]
i think the problem is taranis uses fxx or something instead of ppm to communicate with the internal module.

i just tried ppm2 and its not working im not getting anything from it.

**Comment by LTMNO** [comment]
Yes, it uses pxx for the XJT internal module.

**Comment by adriano65** [comment]
Thank you for directions.
My taranis connect correctly with receiver, but
No telemetry is displayed.
With original opentx it is ok :-(

**Comment by geofrancis** [comment]
have they done something weird like inverted it?

**Comment by adriano65** [comment]
Yes, taranis has inverted serial levels (unlike our glorious 9xrpro/sky9x)
but the original 2.0.14 opentx can manage them in some way...
Anyway, i should have fixed the menus on 9xr-pro, check prereleases :-)

**Comment by FlyingHighInTheSky** [comment]
@adriano65  Are you only working on 9xr pro. Any new features for 9xr.

**Comment by adriano65** [comment]
@albeagle007 
Sincerely, i started working on my old-but-rocky-sky9x to have only one radio with frsky/mavlink.
Last year I buy a Taranis+ to have these useful side-pots for pan-tilt-cameras.
I own two 9x and one friend's 9xr but, even with your help, I can't join all TXes code together.

.. and spring is coming :-) no more long (programming) nights :-)

**Comment by FlyingHighInTheSky** [comment]
;)

**Comment by geofrancis** [comment]
did you get pxx working? 

the stock xjt wont work in a stock 9xr pro with telemetry like it does with er9x since you cannot enable PXX instead of ppm in external rf module output.

**Comment by adriano65** [comment]
Taranis internal module works now! We have to set serial speed @ 57600 unlike external
modules (9600 baud).
Companion doesn't load/save eeprom properly, but i hope to fix it soon
@geofrancis
i will check code to enable PXX on 9xr-pro

**Comment by geofrancis** [comment]
Any joy on the pxx with 9xr pro?

**Comment by adriano65** [comment]
I enabled PXX on 0.2.20 pre-release, but as usual I haven't test it ;-)
BUT, in various merging done to solve taranis PPM problems I disabled 9XR-PRO second PPM out.

**Comment by geofrancis** [comment]
9xr pro ppm2 did not work on the last version I have tried so I have just spliced the internal module to the bay.

**Comment by geofrancis** [comment]
As far as I can tell no one else has got pxx working on a 9xr pro with opentx. I'm having to use er9x with xjt.

The other thing was would you be able to make the mavlink values part of the menus so you can assign voice alarms to voltage like you can with frsky.

**Comment by adriano65** [comment]
Hi geofrancis,
i prereleased 0.2.21 for 9xr-pro with PPM2 re-enabled. Not tested :-(
About mavlink alarms integration, it is on my list, but before
i want fix companion to save models...
nice day

**Comment by geofrancis** [comment]
Cool thanks

**Comment by burbulence** [comment]
I've just stumbled across this which seems to be able to solve all my issues potentially. I have a 9x radio and between my land sea and sky models I use frsky telemetry for all but the quadcopter. 
Does this work with frsky radio modules or is it only openlrs modules? Also is there a how to or a wiki fortheproject other than GitHub? Thanks

**Comment by adriano65** [comment]
hi burbulence,
this fw works with frsky external modules or openlrsng modules.
you must mod 9x to connect serial tx-rx from external modules to atmega64
processor (you can find all info on youtube ecc)
Try https://github.com/adriano65/opentx-2.0.14/tree/0.2.17 prerelease binaries
Beware, NO support for model backup/restore (companion)

No wiki/forum for now

**Comment by burbulence** [comment]
Hi Adriano,

Thanks for the reply. I have modded the 9x to receive telemetry data from the frsky djt module. Is the mavlink data transmitted through the frsky data port, or do you need to connect a 3dr telemetry module to the tx rx ports?
 Do you compile with arduino or direct from Linux?

**Comment by adriano65** [comment]
Mavlink data can be received by 9x on same txrx pins used by frsky module.
you have to connect receiver on plane to autopilot (i use APM) and
configure openlrsng for a clear serial channel.
Then mavlink data can reach 9x and be decoded by my FW.
Albeagle007 has a nice tutorial on his site.

**Comment by burbulence** [comment]
Is it possible to use frsky D series transmitter and receiver modules or do they have to be openlrsng.  Currently I have 
APM>frsky D8-rxp>Frsky DJT module >modded 9x. 
 I'm using modded er9x on my transmitter and have a arduino mini on the quad converting mavlink to frsky protocol, it's great apart from limited functionality er9x has compared with opentx, that being the reason this system is interesting me so much!

**Comment by adriano65** [comment]
With my FW you can use both frsky or mavlink.
Please note i haven't yet developed a companion interface, so
backup all your model before try thi FW

**Comment by geofrancis** [comment]
i am still using your firmware, the only thing i am really missing is voice alerts for mavlink telemetry

**Comment by adriano65** [comment]
Sorry for late anwer,
I suspended working on FW and i think i resume on october..
The priority will be companion to transfer model between new FW version
anyway.
..or find a way to use original companion
